Fixed: With some compilers, calling Threads::Task::Task() with a
function object that ends with an exception lead to a segmentation
fault. This is now fixed.
<br>
(Wolfgang Bangerth, 2023/06/26)
